name = "portfolio"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[env.production]
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://portfolio-e5u.pages.dev"
NEXT_PUBLIC_CONTACT_EMAIL = "gokul@addtocloud.tech"

# Environment variables for production
[vars]
NEXT_PUBLIC_CONTACT_EMAIL = "gokul@addtocloud.tech"

# Secrets (set via wrangler secret put or GitHub Actions)
# Email service API keys (choose one)
# RESEND_API_KEY
# EMAILJS_SERVICE_ID
# EMAILJS_TEMPLATE_ID
# EMAILJS_PUBLIC_KEY
# EMAILJS_PRIVATE_KEY
# SMTP2GO_API_KEY

# Legacy SMTP configurations
# SMTP_HOST
# SMTP_PORT  
# SMTP_USER
# SMTP_PASSWORD
# ZOHO_SMTP_HOST
# ZOHO_SMTP_PORT
# ZOHO_SMTP_USER
# ZOHO_SMTP_PASSWORD

# Cloudflare configuration
# CLOUDFLARE_API_TOKEN
# CLOUDFLARE_ACCOUNT_ID
# CLOUDFLARE_ZONE_ID
